### ISSUE TITLE
请求合并 oraxen配置

### ISSUE THREAD

**Issue by postyizhan** [LSDog/CustomSprays#12]
[oraxen](https://www.spigotmc.org/resources/.72448/)与[Itemsadder](https://www.spigotmc.org/resources/.73355/)同为资源包管理插件

我做了音效包的oraxen版本：https://github.com/postyizhan/CustomSprays/tree/oraxen

您创建一个oraxen分支，好让我给您提交pr？

**Comment by LSDog** [comment]
ok, [oraxen](https://github.com/LSDog/CustomSprays/tree/oraxen)
