### ISSUE TITLE
喷漆删除仍存在

### ISSUE THREAD

**Issue by MrLgos** [LSDog/CustomSprays#15]
**Describe the bug**
非必现，有时候删除喷漆，喷漆仍存在，需要退出服务器重进才会消失。

**To Reproduce**
1. 版本1.19.4的Paper端
2. 喷小喷漆或大喷漆都可
3. /cspray delete后成功显示喷漆玩家名字，但有概率没清除喷漆
4. 玩家退出服务器后重进可清除

**Expected behavior**
在/cspray delete后成功删除喷漆

**Screenshots**
![image](https://github.com/LSDog/CustomSprays/assets/104048162/d2289e83-af26-42f3-ab84-2520347f6888)

**Information (please complete the following information):**
 - 1.19.4
 - PaperSpigot
 - 客户端1.19.4
 - 插件版本1.5.10

**Comment by LSDog** [comment]
貌似一直有这个问题，我再去检查一下看看

**Comment by LSDog** [comment]
已查明原因。近期修复

**Comment by LSDog** [comment]
1.5.12已修复
