### ISSUE TITLE
Feature request - automatically creatig sprays when player dies (on the ground)

### ISSUE THREAD

**Issue by homerek111** [LSDog/CustomSprays#17]
Sorry if im writing in a wrong place but i have some nice idea for a new feature to improve the plugin...

Proposition:
- make it possible to automatically create spray on the ground when player dies (spray that is about to be created would be defined in config / file - like default spray is) 
- it would be also nice to allow defining more than 1 sprays that are possible to create - so it will pick a random one from the group of defined photos 
- this automatically created sprays would disappear after X time - possible to define in config 

What i am trying to achieve is creating a dead bodies on the ground after player gets killed (example photo below)
![obraz](https://github.com/LSDog/CustomSprays/assets/93496464/f491a5be-97cf-40ff-ac87-cefd95898f08)

I know this feature is "something extra" than basic use of the plugin but i think many players would find it very useful :D

**Comment by LSDog** [comment]
Cool idea, I think I can add this feature when I have some spare time

**Comment by homerek111** [comment]
> Cool idea, I think I can add this feature when I have some spare time

Nice! I hope you find some time for that asap :))

**Comment by homerek111** [comment]
> Cool idea, I think I can add this feature when I have some spare time

@LSDog Sorry for spamming but when +/- are you going to implement this feature? I really need that :D

**Comment by LSDog** [comment]
> > Cool idea, I think I can add this feature when I have some spare time
> 
> @LSDog Sorry for spamming but when +/- are you going to implement this feature? I really need that :D

maybe this sunday

**Comment by LSDog** [comment]
Turns out this requires more time for me to code... So sorry that I can't finish the feature this week, and if you can wait I may do it next week.

**Comment by homerek111** [comment]
> Turns out this requires more time for me to code... So sorry that I can't finish the feature this week, and if you can wait I may do it next week.

My dev friend created it for me as an addon to your plugin so I have it running already 🤠

**Comment by LSDog** [comment]
> My dev friend created it for me as an addon to your plugin so I have it running already 🤠

That's great!

**Comment by homerek111** [comment]
> > My dev friend created it for me as an addon to your plugin so I have it running already 🤠
> 
> That's great!

Adding that feature to the main plugin would be useful for plugin users - consider adding it anyway :)

**Comment by LSDog** [comment]
okay, there will be one day i finish this
