### ISSUE TITLE
New Developer API Feature

### ISSUE THREAD

**Issue by PantherPK** [LSDog/CustomSprays#18]
Hi, I don't know if I'm writing this in the right place, but I need one DEV API function.

I'm making a server based on GTA, I'd like to add spraying only important places, could you implement a PlayerSprayEvent event with the ability to check the location of spraying, by which player and the ability to cancel?

Need to contact with me? Reach me on discord: @pantherpk

**Comment by LSDog** [comment]
Just added [PlayerSprayEvent.java](https://github.com/LSDog/CustomSprays/blob/master/src/fun/LSDog/CustomSprays/PlayerSprayEvent.java), but I didn't test it, you can build it and try it out
**PS: The config.yml has changed, you need to modify your config keys and `configVersion` according to [*this commit*](https://github.com/LSDog/CustomSprays/commit/416e4529317ead436188e4124d8b1eabe4d8d50c#diff-509bf82d82607135c37157b49ed63e89320ff70aa09d597bdef99945180207a8)

**Comment by LSDog** [comment]
@PantherPK hello, any chance to test it and give a feedback? (I don't have any time debugging these days so if you are free to do this...)
