### ISSUE TITLE
Spray not working on 1.20.2

### ISSUE THREAD

**Issue by CryLegende** [LSDog/CustomSprays#23]
**Describe the bug**
1.20.2 still isn't working for me, no error, and debug message OK, I even have particles showing, but not the image.
Something seems to be placed, since I can click where the spray is  supposed to be, and my name show up in the chat, so this can be a packet problem maybe ?

`[CustomSprays][DEBUG] Cry_Legende spray -> -23.0 71.0 129.0`

Thank you for your help ! :)

**Informations:**
Purpur 1.20.2 (under latest Waterfall version)
CustomSprays 1.5.14

**Comment by CryLegende** [comment]
Also, before 1.5.12 the plugin was working most of the time ^^

**Comment by LSDog** [comment]
I tried spraying in spigot 1.20.2 and its working (I can't find paper/purpur jar for 1.20.2 now), so I suspect that the problem is that the image is not successfully downloaded, and resulted in nothing shown
![image](https://github.com/user-attachments/assets/e3e55bb5-553d-4d5e-bbe4-1ccb4d3bb0d8)
